name: Trigger COPR build
on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger COPR
        env:
          COPR_WEBHOOK_URL: ${{ secrets.COPR_WEBHOOK_URL }}
        run: |
          curl --fail --silent --show-error \
            -X POST \
            "$COPR_WEBHOOK_URL"
