name: webhook COPR build
on:
  push:
    branches:
      - main
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger COPR build
        env:
          COPR_WEBHOOK_URL: ${{ secrets.COPR_WEBHOOK_URL }}
        run: |
          curl \
            -X POST \
            "$COPR_WEBHOOK_URL"
